export const wordList = {
  a: ["abort", "apple", "ascii"],
  b: ["block", "board", "basic"],
  c: ["click", "crash", "close", "codes"],
  d: ["debug"],
  e: ["email", "excel", "erase"],
  f: ["field", "flash", "forth", "forum", "frame"],
  g: ["gates"],
  h: ["hello"],
  i: ["input", "intel", "image"],
  j: ["jumps"],
  k: ["kings"],
  l: ["laser", "layer", "logic", "login", "logon"],
  m: ["macro", "media", "media", "modem", "mouse", "mysql"],
  n: ["nitro"],
  o: ["octal"],
  p: ["paint", "pixel", "popup", "proxy"],
  q: ["query", "queue"],
  r: ["reset", "robot"],
  s: ["stack", "stats", "suite"],
  t: ["table", "track", "tweet", "techs"],
  u: ["ultra"],
  v: ["virus"],
  w: ["write"],
  x: ["xebec"],
  y: ["yacht"],
  z: ["zebra"],
};
